all:
  children:
    k8s_master:
      hosts:
        master:
          ansible_connection: docker

    workers:
      hosts:
        worker1:
          ansible_connection: docker
        worker2:
          ansible_connection: docker