- hosts: all
  gather_facts: false

  tasks:

    - name: Install python and sudo
      raw: apt update && apt install -y python3 sudo

    - name: Gather facts
      setup:

- hosts: all
  become: true

  tasks:

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install Kubernetes packages
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes